// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function trimEnv(v: string | undefined): string {
  if (v == null || v === '') return '';
  return String(v).trim().replace(/^"|"$/g, '').replace(/^['"]|['"]$/g, '');
}

function envVar(name: string): string {
  try {
    const metaEnv = (import.meta as any)?.env;
    const v = metaEnv?.[name];
    if (typeof v === 'string' && v.trim()) return trimEnv(v);
  } catch {
    /* ignore */
  }

  try {
    const pe = (process as any)?.env || {};
    const v = pe[name] ?? pe[`NEXT_PUBLIC_${name}`];
    if (typeof v === 'string' && v.trim()) return trimEnv(v);
  } catch {
    /* ignore */
  }

  return '';
}

const SUPABASE_URL = envVar('VITE_SUPABASE_URL');
/** Legacy anon JWT (eyJ…) from Dashboard → API. Prefer this if Edge Functions return "Invalid JWT" with a publishable key. */
const SUPABASE_ANON_KEY = envVar('VITE_SUPABASE_ANON_KEY');
const SUPABASE_PUBLISHABLE_KEY = envVar('VITE_SUPABASE_PUBLISHABLE_KEY');
const SUPABASE_KEY = SUPABASE_ANON_KEY || SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error(
    'Missing Supabase env vars. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY or VITE_SUPABASE_PUBLISHABLE_KEY to .env and restart the dev server.'
  );
}

/** One storage bucket per project ref so switching .env URL does not reuse another project's session. */
function authStorageKey(url: string): string {
  try {
    const host = new URL(url).hostname;
    const ref = host.split('.')[0] || 'local';
    return `sb-${ref}-auth-token`;
  } catch {
    return 'sb-auth-token';
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    storageKey: authStorageKey(SUPABASE_URL),
    persistSession: true,
    autoRefreshToken: true,
  },
});